runtime: python39 # or another supported version
#instance_class: F1 # this is the cheapest option
env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'team87'
  MYSQL_DB: 'db_pc'
  MYSQL_HOST: '35.193.220.207'

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /styles
  static_dir: static/styes
- url: /script
  static_dir: static/script

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  
